server:
  port: 9090
spring:
  datasource:
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/ms-user
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: liquibase/changelog-master.yml
    enabled: true
    drop-first: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
client:
  urls:
    ms-orders: http://localhost:8080
